version: "3.8"

services:
  web:
    build: .
    container_name: mini-amazon-web
    ports:
      - "8080:8080" # 宿主机5001->容器5000
    volumes:
      - .:/app
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      FLASK_RUN_PORT: 8080
      DATABASE_URL: postgresql://postgres:abc123@db:5432/mini_amazon
      SECRET_KEY: dev
      WORLD_HOST: docker_deploy-server-1 # 与另一个 compose 里的 container_name 一致
      WORLD_PORT: "23456"
    depends_on:
      - db
    networks:
      - projectnet

  db:
    image: postgres:12-alpine3.15
    container_name: mini-amazon-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: abc123
      POSTGRES_USER: postgres
      POSTGRES_DB: mini_amazon
    ports:
      - "15432:5432"
    networks:
      - projectnet

networks:
  projectnet:
    external: true

volumes:
  postgres_data:
