version: "3.8"

services:
  web:
    build: .
    container_name: mini-amazon-web
    ports:
      - "5001:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app
      FLASK_ENV: development
      DATABASE_URL: postgresql://postgres:abc123@db:5432/mini_amazon
      SECRET_KEY: dev
      WORLD_HOST: server
      WORLD_PORT: "23456"
    depends_on:
      - db
    networks:
      - project-network

  db:
    image: postgres:12-alpine3.15
    container_name: mini-amazon-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_PASSWORD: abc123
      POSTGRES_USER: postgres
      POSTGRES_DB: mini_amazon
    ports:
      - "5432:5432"
    networks:
      - project-network

networks:
  project-network:
    external: true

volumes:
  postgres_data:
